apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: my-space/auth-server:v1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker,prod"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
