apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: my-space/config:v1
        env:
          - name: LOGGING_LEVEL_ROOT
            value: WARN
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: "health,info"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
